# serverless.yml

service: s3-db

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  memorySize: 3008 # Overwrite the default memory size. Default is 1024
  timeout: 30 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
  logRetentionInDays: 1 # Set the default RetentionInDays for a CloudWatch LogGroup

functions:
  app:
    handler: app.handler
    events:
      - http:
          path: parse
          method: get
          cors: true
          
plugins:
  - serverless-offline
  